#!/usr/bin/env node
/**
 * Inter-module dependency map for the Department Dashboard Apps Script project.
 *
 * Why this needs to exist: Apps Script has ONE global scope per project -- every
 * .gs file's top-level functions and constants are visible to every other file,
 * with no imports to read. So the dependency graph that would be obvious from
 * `import` statements in a normal codebase is INVISIBLE here: the only way to
 * know that Config.gs is reachable from 37 of 39 files is to compute it. That
 * matters because it is the difference between "a local edit" and "a
 * whole-project change", and nothing in the repo said which was which.
 *
 * Why it is a GENERATOR and not a hand-written table: fan-out counts drift on
 * every file added or helper moved, and a stale architecture number is worse
 * than none -- it gets trusted. Regenerating is one command, so the map is
 * cheap to keep true (the B-2 lesson: prose could not keep a structural claim
 * true, a tripwire could).
 *
 * Method + its limits (stated so nobody over-trusts the output):
 *   - Definitions: top-level `function NAME(` plus top-level SCREAMING_CASE
 *     const/var/let. Nested helpers are deliberately NOT indexed -- they are
 *     not reachable across files anyway.
 *   - References: a word-boundary match of a symbol in another file, AFTER
 *     comments are stripped. It is a HEURISTIC, not a parse: a symbol named
 *     inside a string literal (a Pipeline Health step name, say) still counts.
 *     Treat the numbers as magnitudes, not exact call counts.
 *   - The direction that matters is DEPENDED-ON-BY (incoming): how much breaks
 *     if this file changes.
 *
 * Usage:
 *   node scripts/module-deps.mjs            # print the map to stdout
 *   node scripts/module-deps.mjs --write    # regenerate docs/module-dependencies.md
 *   node scripts/module-deps.mjs --check    # exit 1 if that doc is out of date
 *
 * --check is NOT wired into CI on purpose: adding one .gs file legitimately
 * shifts every count, and a gate that fails on ordinary work trains people to
 * ignore it. Run it when you want to know, or after touching the .gs set.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC_DIR = path.join(ROOT, 'apps-script', 'department-dashboard');
const DOC = path.join(ROOT, 'docs', 'module-dependencies.md');
const BEGIN = '<!-- BEGIN GENERATED: node scripts/module-deps.mjs --write -->';
const END = '<!-- END GENERATED -->';

/** Strip block + line comments so a symbol named only in prose does not count. */
function stripComments(s) {
  return s
    .replace(/\/\*[\s\S]*?\*\//g, ' ')
    .replace(/^[ \t]*\/\/.*$/gm, ' ')
    .replace(/([^:'"`\\])\/\/.*$/gm, '$1 ');
}

function analyze() {
  const files = fs.readdirSync(SRC_DIR).filter((f) => f.endsWith('.gs')).sort();
  const defs = new Map();   // symbol -> defining file
  const body = new Map();   // file -> comment-stripped source

  for (const f of files) {
    const raw = fs.readFileSync(path.join(SRC_DIR, f), 'utf8');
    body.set(f, stripComments(raw));
    for (const m of raw.matchAll(/^function\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(/gm)) {
      if (!defs.has(m[1])) defs.set(m[1], f);
    }
    for (const m of raw.matchAll(/^(?:const|var|let)\s+([A-Z][A-Z0-9_]{2,})\s*=/gm)) {
      if (!defs.has(m[1])) defs.set(m[1], f);
    }
  }

  const dependsOn = new Map(files.map((f) => [f, new Set()]));
  const symUsers = new Map();   // symbol -> count of OTHER files referencing it

  for (const f of files) {
    const src = body.get(f);
    for (const [sym, owner] of defs) {
      if (owner === f) continue;
      if (!new RegExp(`\\b${sym}\\b`).test(src)) continue;
      dependsOn.get(f).add(owner);
      symUsers.set(sym, (symUsers.get(sym) || 0) + 1);
    }
  }

  const incoming = new Map(files.map((f) => [f, 0]));
  for (const f of files) for (const d of dependsOn.get(f)) incoming.set(d, incoming.get(d) + 1);

  const rows = files.map((f) => ({
    file: f,
    in: incoming.get(f),
    out: dependsOn.get(f).size,
    kb: Math.round(fs.statSync(path.join(SRC_DIR, f)).size / 1024),
    pct: Math.round((incoming.get(f) / (files.length - 1)) * 100),
  })).sort((a, b) => b.in - a.in || a.file.localeCompare(b.file));

  const symbols = [...symUsers.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .slice(0, 25)
    .map(([sym, n]) => ({ sym, n, owner: defs.get(sym) }));

  return { files, rows, symbols, defCount: defs.size };
}

function render({ files, rows, symbols, defCount }) {
  const out = [];
  out.push(`_${files.length} \`.gs\` files, ${defCount} top-level symbols. Generated by \`scripts/module-deps.mjs\` — do not hand-edit this section._`);
  out.push('');
  out.push('### Fan-out per module');
  out.push('');
  out.push('`Depended on by` is the number of OTHER files referencing a symbol this file defines — the blast radius of changing it. `Depends on` is the reverse.');
  out.push('');
  out.push('| Module | Depended on by | % of project | Depends on | KB |');
  out.push('|---|---:|---:|---:|---:|');
  for (const r of rows) {
    out.push(`| \`${r.file}\` | ${r.in} | ${r.pct}% | ${r.out} | ${r.kb} |`);
  }
  out.push('');
  out.push('### Most-shared symbols');
  out.push('');
  out.push('| Symbol | Referenced in N other files | Defined in |');
  out.push('|---|---:|---|');
  for (const s of symbols) out.push(`| \`${s.sym}\` | ${s.n} | \`${s.owner}\` |`);
  return out.join('\n');
}

function main() {
  const arg = process.argv[2];
  const generated = render(analyze());

  if (arg === '--write' || arg === '--check') {
    if (!fs.existsSync(DOC)) {
      console.error(`${path.relative(ROOT, DOC)} does not exist yet — create it with the ${BEGIN} / ${END} markers first.`);
      process.exit(1);
    }
    const doc = fs.readFileSync(DOC, 'utf8');
    const i = doc.indexOf(BEGIN);
    const j = doc.indexOf(END);
    if (i === -1 || j === -1 || j < i) {
      console.error(`${path.relative(ROOT, DOC)} is missing the generated-section markers.`);
      process.exit(1);
    }
    const next = doc.slice(0, i + BEGIN.length) + '\n\n' + generated + '\n\n' + doc.slice(j);
    if (arg === '--check') {
      if (next !== doc) {
        console.error('docs/module-dependencies.md is out of date. Refresh it:\n  node scripts/module-deps.mjs --write');
        process.exit(1);
      }
      console.log('docs/module-dependencies.md is up to date.');
      return;
    }
    fs.writeFileSync(DOC, next);
    console.log(`Wrote ${path.relative(ROOT, DOC)}`);
    return;
  }
  console.log(generated);
}

main();
